/**
 * Katalog permission (RBAC granular per module/action — SRS 4.3) dan default role (BRD 1.6).
 * File ini tidak bergantung pada server sehingga bisa dipakai di UI untuk menyembunyikan menu/aksi.
 */
export const PERMISSIONS = {
  // Dashboard
  "dashboard.view": "Melihat dashboard",
  // Customer & kendaraan
  "customer.view": "Melihat customer",
  "customer.create": "Membuat customer",
  "customer.edit": "Mengubah customer",
  "customer.delete": "Menonaktifkan customer",
  "vehicle.view": "Melihat kendaraan",
  "vehicle.create": "Menambah kendaraan",
  "vehicle.edit": "Mengubah kendaraan",
  "vehicle.transfer": "Pindah kepemilikan kendaraan",
  // Booking & check-in
  "booking.view": "Melihat booking",
  "booking.create": "Membuat booking",
  "booking.edit": "Konfirmasi / reschedule booking",
  "booking.cancel": "Membatalkan booking / no show",
  "checkin.view": "Melihat check-in",
  "checkin.create": "Membuat check-in kendaraan",
  "checkin.override_odometer": "Override odometer lebih kecil (BR-015)",
  "checkin.cancel": "Membatalkan check-in",
  // Inspeksi & estimate
  "inspection.view": "Melihat inspeksi",
  "inspection.execute": "Melakukan inspeksi",
  "estimate.view": "Melihat estimate",
  "estimate.create": "Membuat / mengubah estimate",
  "estimate.approve": "Merekam approval customer",
  "estimate.cancel": "Membatalkan estimate",
  // Work order & mekanik
  "workorder.view": "Melihat seluruh Work Order",
  "workorder.create": "Membuat Work Order",
  "workorder.edit": "Mengubah Work Order (prioritas, bay, status)",
  "workorder.assign": "Menugaskan mekanik",
  "workorder.cancel": "Membatalkan Work Order",
  "workorder.price_override": "Mengubah harga setelah approval (BR-010)",
  "job.execute": "Mengerjakan job (start/pause/resume/complete)",
  // Parts & inventory
  "partrequest.view": "Melihat permintaan part",
  "partrequest.create": "Membuat permintaan part",
  "inventory.view": "Melihat stok & mutasi",
  "inventory.issue": "Issue / return part",
  "inventory.receive": "Penerimaan barang (receiving)",
  "inventory.adjust": "Stock adjustment / opname",
  "inventory.transfer": "Transfer stok antar gudang",
  "part.manage": "Kelola master spare part",
  "service.manage": "Kelola master jasa",
  "supplier.manage": "Kelola supplier",
  "purchase.view": "Melihat purchase order",
  "purchase.create": "Membuat purchase order",
  "purchase.approve": "Menyetujui / membatalkan purchase order",
  // QC
  "qc.view": "Melihat antrian QC",
  "qc.execute": "Melakukan QC (Pass/Fail/Rework)",
  // Kasir
  "invoice.view": "Melihat invoice",
  "invoice.create": "Membuat invoice / penjualan langsung",
  "invoice.discount": "Memberi diskon tambahan di invoice",
  "invoice.void": "Void invoice",
  "payment.view": "Melihat pembayaran",
  "payment.receive": "Menerima pembayaran",
  "payment.void": "Void pembayaran",
  "payment.refund": "Refund pembayaran",
  "payment.receivable": "Otorisasi piutang (tempo)",
  "handover.execute": "Serah terima kendaraan",
  "handover.override": "Override syarat serah terima (BR-008)",
  // CRM
  "reminder.view": "Melihat service reminder",
  "reminder.manage": "Follow-up service reminder",
  // Laporan
  "report.operational.view": "Laporan operasional",
  "report.sales.view": "Laporan penjualan",
  "report.inventory.view": "Laporan inventory",
  "report.customer.view": "Laporan customer",
  "report.finance.view": "Laporan finance",
  "audit.view": "Melihat audit log",
  // Settings
  "settings.company": "Pengaturan perusahaan, pajak & penomoran",
  "settings.branch": "Kelola cabang & gudang",
  "settings.user": "Kelola user",
  "settings.role": "Kelola role & permission",
  "settings.master": "Kelola master (metode bayar, merk, template inspeksi)",
} as const;

export type Permission = keyof typeof PERMISSIONS;
export const ALL_PERMISSIONS = Object.keys(PERMISSIONS) as Permission[];

export const PERMISSION_MODULE_LABELS: Record<string, string> = {
  dashboard: "Dashboard",
  customer: "Customer",
  vehicle: "Kendaraan",
  booking: "Booking",
  checkin: "Check-In",
  inspection: "Inspeksi",
  estimate: "Estimate",
  workorder: "Work Order",
  job: "Mekanik",
  partrequest: "Permintaan Part",
  inventory: "Inventory",
  part: "Master Part",
  service: "Master Jasa",
  supplier: "Supplier",
  purchase: "Purchasing",
  qc: "Quality Control",
  invoice: "Invoice",
  payment: "Pembayaran",
  handover: "Serah Terima",
  reminder: "CRM / Reminder",
  report: "Laporan",
  audit: "Audit",
  settings: "Settings",
};

const p = (...codes: Permission[]) => codes;
const reports = p(
  "report.operational.view",
  "report.sales.view",
  "report.inventory.view",
  "report.customer.view",
  "report.finance.view",
);
const viewAll = p(
  "dashboard.view",
  "customer.view",
  "vehicle.view",
  "booking.view",
  "checkin.view",
  "inspection.view",
  "estimate.view",
  "workorder.view",
  "partrequest.view",
  "inventory.view",
  "purchase.view",
  "qc.view",
  "invoice.view",
  "payment.view",
  "reminder.view",
);

export type RoleDefinition = {
  name: string;
  description: string;
  allBranches: boolean;
  permissions: Permission[];
};

/** Role default sesuai BRD 1.6 Role dan Tanggung Jawab */
export const DEFAULT_ROLES: RoleDefinition[] = [
  {
    name: "Super Admin",
    description: "Konfigurasi perusahaan, cabang, user, role, permission, master data dan seluruh sistem.",
    allBranches: true,
    permissions: ALL_PERMISSIONS,
  },
  {
    name: "Owner / Management",
    description: "Dashboard, analytics, laporan dan monitoring lintas cabang sesuai otorisasi.",
    allBranches: true,
    permissions: [...viewAll, ...reports, "audit.view", "payment.receivable", "handover.override", "workorder.price_override"],
  },
  {
    name: "Branch Manager",
    description: "Monitoring operasional dan transaksi cabang.",
    allBranches: false,
    permissions: [
      ...viewAll,
      ...reports,
      "audit.view",
      "booking.cancel",
      "checkin.create",
      "checkin.override_odometer",
      "checkin.cancel",
      "estimate.cancel",
      "workorder.cancel",
      "workorder.price_override",
      "invoice.void",
      "invoice.discount",
      "payment.void",
      "payment.refund",
      "payment.receivable",
      "handover.execute",
      "handover.override",
      "inventory.adjust",
      "purchase.approve",
      "reminder.manage",
    ],
  },
  {
    name: "Workshop Supervisor",
    description: "Work Order, mechanic assignment, workshop board, QC/rework coordination.",
    allBranches: false,
    permissions: [
      "dashboard.view",
      "customer.view",
      "vehicle.view",
      "checkin.view",
      "inspection.view",
      "inspection.execute",
      "estimate.view",
      "workorder.view",
      "workorder.create",
      "workorder.edit",
      "workorder.assign",
      "job.execute",
      "partrequest.view",
      "partrequest.create",
      "inventory.view",
      "qc.view",
      "qc.execute",
      "report.operational.view",
    ],
  },
  {
    name: "Service Advisor",
    description: "Customer, kendaraan, check-in, inspection, estimate, approval, WO.",
    allBranches: false,
    permissions: [
      "dashboard.view",
      "customer.view",
      "customer.create",
      "customer.edit",
      "vehicle.view",
      "vehicle.create",
      "vehicle.edit",
      "vehicle.transfer",
      "booking.view",
      "booking.create",
      "booking.edit",
      "booking.cancel",
      "checkin.view",
      "checkin.create",
      "inspection.view",
      "inspection.execute",
      "estimate.view",
      "estimate.create",
      "estimate.approve",
      "estimate.cancel",
      "workorder.view",
      "workorder.create",
      "workorder.edit",
      "partrequest.view",
      "inventory.view",
      "qc.view",
      "invoice.view",
      "handover.execute",
      "reminder.view",
      "reminder.manage",
    ],
  },
  {
    name: "Mechanic",
    description: "Melihat job, start/pause/resume/complete, request part, job notes.",
    allBranches: false,
    permissions: ["job.execute", "partrequest.create", "partrequest.view", "inspection.view", "inspection.execute"],
  },
  {
    name: "QC",
    description: "Melakukan pemeriksaan akhir dan menetapkan Pass/Fail/Rework.",
    allBranches: false,
    permissions: ["dashboard.view", "vehicle.view", "workorder.view", "qc.view", "qc.execute", "inspection.view"],
  },
  {
    name: "Parts Staff",
    description: "Part request, receiving, issue, stock movement, stock opname.",
    allBranches: false,
    permissions: [
      "dashboard.view",
      "partrequest.view",
      "inventory.view",
      "inventory.issue",
      "inventory.receive",
      "inventory.adjust",
      "inventory.transfer",
      "part.manage",
      "purchase.view",
      "report.inventory.view",
    ],
  },
  {
    name: "Purchasing",
    description: "Purchase request/order dan supplier.",
    allBranches: false,
    permissions: [
      "dashboard.view",
      "inventory.view",
      "inventory.receive",
      "part.manage",
      "supplier.manage",
      "purchase.view",
      "purchase.create",
      "purchase.approve",
      "report.inventory.view",
    ],
  },
  {
    name: "Cashier",
    description: "Invoice, payment, receipt dan closing kasir.",
    allBranches: false,
    permissions: [
      "dashboard.view",
      "customer.view",
      "customer.create",
      "vehicle.view",
      "workorder.view",
      "inventory.view",
      "invoice.view",
      "invoice.create",
      "payment.view",
      "payment.receive",
      "handover.execute",
      "report.sales.view",
    ],
  },
  {
    name: "Accounting",
    description: "Finance report, AR, rekonsiliasi/integrasi accounting.",
    allBranches: true,
    permissions: ["dashboard.view", "invoice.view", "payment.view", "inventory.view", "report.sales.view", "report.finance.view", "report.inventory.view", "audit.view"],
  },
  {
    name: "Customer Service",
    description: "Booking, reminder, follow-up dan CRM.",
    allBranches: false,
    permissions: [
      "dashboard.view",
      "customer.view",
      "customer.create",
      "customer.edit",
      "vehicle.view",
      "vehicle.create",
      "booking.view",
      "booking.create",
      "booking.edit",
      "booking.cancel",
      "reminder.view",
      "reminder.manage",
      "report.customer.view",
    ],
  },
];
